/**
 * Promote a validated candidate manifest and synchronize compatible consumers.
 * Dry-run is the default. Pass --apply to write and --yes to acknowledge impact.
 */
import fs from "node:fs";
import path from "node:path";
import {
  CANONICAL_MANIFEST,
  candidateManifestPath,
  SuiteManifest,
  validateCompleteSuite,
  validateManifestSchema,
} from "./suite-manifest";

type Consumer = { path: string; requiredKeys: string[] };

const CONSUMERS: Consumer[] = [
  {
    path: path.join(__dirname, "..", "..", "agents", "deployments", "base-8453.json"),
    requiredKeys: [
      "chainId", "network", "usdc", "azlToken", "feeRecipient", "deployer",
      "EscrowVault", "TaskRegistry", "ReputationRegistry", "ArbitrationModule",
      "ArbitrationSatellite", "ArbitrationRecoveryCoordinator", "TreasuryRouter",
      "AgentDepositVault", "UnionStakingVault", "TaskScopeRegistry",
    ],
  },
  {
    path: path.join(__dirname, "..", "..", "api", "lib", "contracts.json"),
    requiredKeys: [
      "chainId", "network", "usdc", "azlToken", "feeRecipient", "buybackExecutor",
      "fallbackResolver", "deployer", "EscrowVault", "TaskRegistry",
      "ReputationRegistry", "ArbitrationModule", "ArbitrationSatellite",
      "ArbitrationRecoveryCoordinator", "TreasuryRouter", "AgentDepositVault",
      "UnionStakingVault", "TaskScopeRegistry",
    ],
  },
];

const ROOT = path.join(__dirname, "..", "..");
const X402_MANIFEST = path.join(ROOT, "agents", "x402-cloud", "x402", "manifest.ts");
const LAUNCH_MANIFEST = path.join(ROOT, "launch-skills", "js", "manifest.generated.js");
const SAFE_BATCH = path.join(__dirname, "..", "deployments", "accept-ownership-safe-batch.json");
const OWNABLE_CONTRACTS = [
  "EscrowVault", "TaskRegistry", "ReputationRegistry", "ArbitrationModule",
  "ArbitrationRecoveryCoordinator", "TreasuryRouter", "AgentDepositVault", "UnionStakingVault",
] as const;

/**
 * Addresses in static prose are convenience links, not a source of truth.
 * Updating them as part of promotion prevents a newly promoted suite from
 * being mixed with old BaseScan/manual-execution destinations.
 */
const STATIC_SURFACES = [
  "README.md", "BOOTSTRAP.md", "MASTERSKILL.md", "SPEEDPATH.md",
  "launch-skills/launch-skills.md", "launch-skills/treasury-dashboard.html",
  "docs/X402_CLOUD.md", "agents/x402-cloud/README.md",
  "site/index.html", "site/docs/contracts.html", "site/docs/api.html",
  "site/docs/system-simulation.html", "agents/mcp/skills/azzle/plugins/azzle.md",
];
const DOCUMENTATION_ROOTS = ["docs", "site/docs"];
const DOCUMENTATION_EXTENSIONS = new Set([".md", ".html", ".txt", ".yaml", ".yml"]);

function load(file: string): unknown {
  return JSON.parse(fs.readFileSync(file, "utf8"));
}

function synchronizeConsumer(candidate: SuiteManifest, consumer: Consumer): object {
  const existing = load(consumer.path);
  if (!existing || typeof existing !== "object" || Array.isArray(existing)) {
    throw new Error(`${consumer.path} schema is not an object`);
  }
  const target = existing as Record<string, unknown>;
  const unsupported = Object.keys(target).filter((key) => !(key in candidate));
  if (unsupported.length > 0) {
    throw new Error(`${consumer.path} has unsupported fields (${unsupported.join(", ")}); refusing schema guess`);
  }
  for (const key of consumer.requiredKeys) {
    if (!(key in candidate)) throw new Error(`Candidate cannot satisfy ${consumer.path}: ${key}`);
  }
  return Object.fromEntries(
    [...new Set([...Object.keys(target), ...consumer.requiredKeys])]
      .map((key) => [key, candidate[key as keyof SuiteManifest]])
  );
}

function atomicWrite(file: string, value: object) {
  const temporary = `${file}.tmp-${process.pid}`;
  fs.writeFileSync(temporary, JSON.stringify(value, null, 2) + "\n", { flag: "wx" });
  fs.renameSync(temporary, file);
}

function atomicWriteText(file: string, value: string) {
  const temporary = `${file}.tmp-${process.pid}`;
  fs.writeFileSync(temporary, value, { flag: "wx" });
  fs.renameSync(temporary, file);
}

function generatedTsManifest(candidate: SuiteManifest): string {
  return [
    "// GENERATED by contracts/scripts/promote-manifest.ts. Do not edit.",
    `export const BASE_MAINNET_MANIFEST = ${JSON.stringify(candidate, null, 2)} as const;`,
    "",
  ].join("\n");
}

function generatedBrowserManifest(candidate: SuiteManifest): string {
  return [
    "// GENERATED by contracts/scripts/promote-manifest.ts. Do not edit.",
    `export const MANIFEST = ${JSON.stringify(candidate, null, 2)};`,
    "export const AZL_TOKEN = MANIFEST.azlToken;",
    "",
  ].join("\n");
}

function safeBatch(candidate: SuiteManifest): object {
  return {
    version: "1.0",
    chainId: candidate.chainId,
    createdAt: Date.now(),
    meta: {
      name: "AZZLE protocol ownership acceptance",
      description: "GENERATED FROM base-8453.json; regenerate after every promotion.",
      txBuilderVersion: "1.18.0",
      createdFromSafeAddress: candidate.buybackExecutor,
      checksum: "",
    },
    transactions: OWNABLE_CONTRACTS.map((name) => ({
      to: candidate[name],
      value: "0",
      data: null,
      contractMethod: { inputs: [], name: "acceptOwnership", payable: false },
      contractInputsValues: {},
    })),
  };
}

function x402ServiceManifest(candidate: SuiteManifest): object {
  const file = path.join(ROOT, "agents", "x402-cloud", "bankr.x402.json");
  const current = load(file) as { services?: Record<string, Record<string, unknown>> };
  if (!current.services) throw new Error(`${file} is missing services`);
  for (const service of Object.values(current.services)) service.tokenAddress = candidate.azlToken;
  return current;
}

function replaceStaticAddresses(content: string, from: SuiteManifest, to: SuiteManifest): string {
  let next = content;
  for (const [key, oldAddress] of Object.entries(from)) {
    const newAddress = to[key as keyof SuiteManifest];
    if (typeof oldAddress === "string" && typeof newAddress === "string" && oldAddress !== newAddress) {
      next = next.split(oldAddress).join(newAddress);
    }
  }
  return next;
}

function documentationFiles(directory: string): string[] {
  if (!fs.existsSync(directory)) return [];
  const files: string[] = [];
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    const file = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      files.push(...documentationFiles(file));
    } else if (DOCUMENTATION_EXTENSIONS.has(path.extname(entry.name).toLowerCase())) {
      files.push(file);
    }
  }
  return files;
}

async function main() {
  // Hardhat 2.x does not forward arbitrary `hardhat run` script arguments
  // consistently. The package wrapper supplies these explicit environment
  // flags instead, while direct ts-node use may retain the CLI switches.
  const apply = process.env.MANIFEST_PROMOTE_APPLY === "1" || process.argv.includes("--apply");
  const acknowledged = process.env.MANIFEST_PROMOTE_YES === "1" || process.argv.includes("--yes");
  const candidatePath = candidateManifestPath();
  if (!fs.existsSync(candidatePath)) throw new Error(`Candidate not found: ${candidatePath}`);
  const candidate = validateManifestSchema(load(candidatePath));
  await validateCompleteSuite(candidate);

  const canonical = validateManifestSchema(load(CANONICAL_MANIFEST));
  if (canonical.chainId !== candidate.chainId) {
    throw new Error(`Candidate chain ${candidate.chainId} differs from canonical ${canonical.chainId}`);
  }

  const synchronizations = CONSUMERS.map((consumer) => ({
    ...consumer,
    next: synchronizeConsumer(candidate, consumer),
  }));
  console.log(`[manifest] ${apply ? "APPLY" : "DRY RUN"}`);
  console.log("candidate:", candidatePath);
  console.log("canonical:", CANONICAL_MANIFEST);
  for (const consumer of synchronizations) console.log("consumer:", consumer.path);
  console.log("generated:", X402_MANIFEST);
  console.log("generated:", LAUNCH_MANIFEST);
  console.log("generated:", SAFE_BATCH);
  if (!apply) {
    console.log("\nNo files written. Re-run with --apply --yes after reviewing the candidate.");
    return;
  }
  if (!acknowledged) throw new Error("--apply requires --yes");

  const archiveDir = path.join(path.dirname(CANONICAL_MANIFEST), "archive");
  fs.mkdirSync(archiveDir, { recursive: true });
  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  const archive = path.join(archiveDir, `base-8453.${stamp}.json`);
  fs.copyFileSync(CANONICAL_MANIFEST, archive, fs.constants.COPYFILE_EXCL);
  atomicWrite(CANONICAL_MANIFEST, candidate);
  for (const consumer of synchronizations) atomicWrite(consumer.path, consumer.next);
  atomicWriteText(X402_MANIFEST, generatedTsManifest(candidate));
  atomicWriteText(LAUNCH_MANIFEST, generatedBrowserManifest(candidate));
  atomicWrite(path.join(ROOT, "agents", "x402-cloud", "bankr.x402.json"), x402ServiceManifest(candidate));
  atomicWrite(SAFE_BATCH, safeBatch(candidate));
  const staticFiles = new Set(
    STATIC_SURFACES.map((relativePath) => path.join(ROOT, relativePath))
  );
  for (const docsRoot of DOCUMENTATION_ROOTS) {
    for (const file of documentationFiles(path.join(ROOT, docsRoot))) staticFiles.add(file);
  }
  for (const file of staticFiles) {
    if (!fs.existsSync(file)) continue;
    const current = fs.readFileSync(file, "utf8");
    const updated = replaceStaticAddresses(current, canonical, candidate);
    if (updated !== current) atomicWriteText(file, updated);
  }
  console.log(`Archived prior canonical: ${archive}`);
  console.log("Candidate promoted and deployment consumers/static address surfaces synchronized.");
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
